apiVersion: v1
data:
  Taiwan-LCG2_K8S_config.yaml: |+
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXdOekF5TXpJeE9Gb1hEVEk1TURVd05EQXlNekl4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmVOCm1PMS9ZT3dQSFppYXlrUHN4cnhwd2VkUG50YkxMMG4wUkpzbHR2UFJna2RucVZ3OWZWVzRuVzJQWGRRU0tQalIKMURtbDRNMkJlbXBJR2lLbUNzSFdBd2ZieUJ2QXlldVpzWWUzcFBuQjNYTTl5U25rOWRwQ0pwcUhzekg5UUQ4ZwpSUUFJdVVLczV6cm1GWGZsMlNKYmsvSXhsQnJKNlgvbkd1MFVZY3VDSXVBU0dRZHd2SmVHT3Y1S0NFMGY0azVvCkJ6czhieGpSVW9RWUFKdUxSMTlSRU1DV0VscjJoek1CUTMyMkYvN1JZaE9BZmEyL2ZmOEZQK0h2MU85V0dBZTcKUVhaN2E0ZVFwazBWVjdaQ3E2eWVVdWplRWozcEQybVR4Y2xOdkgzT3UzYWJTK3pOVzBPTUE1S0NNZVUrYVdERgpZNW5KaC9KWXJxZ1B3Ykt2UXZrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIQUM4WkFuWmk1dzJNKzlnVXBvdWI3UHBXM3kKZEdrTkh2cVUwTjVQM21pL052MDJ3SHpSK2JjMkR0STlTeWduYW8zTlpDSGVOWlhsWXkzTW1HOVpOcHlWazBUVApNNWFONHJGT0p1MU9tWm0veUZhMmhuOXN6VGRyUzhsTmVIZXIxVlV5blc4L2ZrL0V0RlorYTc2cnVWZFdkN0RnCmtRMlVWdzJvOXRreXFwVUdkdmgvQWJEQkc4UGNpNFVZTzA4SU1xSk9JT3JxVkJ1SnVmNlJPM0ZZSFV0RFlMR0gKSnJ6ZExEMDlkTEFFVHZ4cFJRT3R6NlA5MWNDYk5mT0hvbWZqd0JDR0Z0YnVFUTh2NHZkLzRTdFdQYWhya2NITApReUg5cUJWM0xJQU42anhqYmtENFNNZ05mVkJ0MTJ6MjcxVUpXQ3IxaGwxUTk5MWtMaVZGaE8wckZycz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://202.169.170.52:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJSmRPS3REQW1qSll3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RBMU1EY3dNak15TVRoYUZ3MHlNREExTURZd01qTXlNak5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTl5TXlnVXhLK3dwdlhPUEgKelhOL2k2KzhIZTdBU2JPNHcrTlJZdXBYYmpIS1U3VC9rNjdqNjJadE9ES29rUmdHNS9EM3RCcTRoMkpEc0lobgp2dFJXQ3JldDhrdG9zcUNsbThsa1kva0N5QmN3b1BNcE92YkhjUmhvMFlTenNZZjBuNHRYN2J0VTNSa3Y3NmhBCnROaXFtQTlTUmR5TlhMVmxkRS8xZmkza3V2S0g1MWVZMUMyb0tNTE1ndjFlL1NVWVBYVjA2Y1haazVnUFZmekIKcFR2ODhwUlFTWkE5bmFidHFhM1ZrSnFzblZkSWFtQTRnVy9xMHdRNU4waUgyK0lDOUY1UjVCQStueVQwRkpySQplRzJEekNtOGVRNlRlckxsa2ZZZ3V0dDFhdVloTkNicTNCZDZNWUFNbmFkRE94Q1gySHpYaE5JZklwTGQzQjR4CjlnVGg0d0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEOFhCMzRQZlg4ckVGS3IzV3hpSTA1VzV5d3NjM28yVDRMUwpUbmVtd21nREhxMzlRQXNyYVdZZndCNUJrWXdjeXlLSEZ2SksvaGtXbWMxMUtEME1BTnRuODdxZ1lzeWo3cWc3ClJqMWoyTGRkNVE2dVhDZ1VtOGNreXJsaU9TV0IyQmFtRmR2LzBiZHRoSmhEZDd1d3U2VWVpL1ZZa2h6ZU9wZUoKWXQ5NEt3TWhTTlZpSHJ0WkFIbEFOWnI0V2dDbGVnM04yeG03V3hCajRSQ1FwQ0ZMY3pZWi85UmFSMTJuZzdSbwpTZjQ3VThGWExESWt1dHI5N1pVYmp0QkJVaUxnTkFDZWU0MjdsOERLcDBtd3BMMWpxTGhLWGhPQkNvQlZRWGxtCllQQU4zQytsOEt5SHBsZWlGQmlYSXNDOWYvaW9HeDFNQ09sYkd6b1MyM2N1NWRPdjBVaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBOXlNeWdVeEsrd3B2WE9QSHpYTi9pNis4SGU3QVNiTzR3K05SWXVwWGJqSEtVN1QvCms2N2o2Mlp0T0RLb2tSZ0c1L0QzdEJxNGgySkRzSWhudnRSV0NyZXQ4a3Rvc3FDbG04bGtZL2tDeUJjd29QTXAKT3ZiSGNSaG8wWVN6c1lmMG40dFg3YnRVM1Jrdjc2aEF0TmlxbUE5U1JkeU5YTFZsZEUvMWZpM2t1dktINTFlWQoxQzJvS01MTWd2MWUvU1VZUFhWMDZjWFprNWdQVmZ6QnBUdjg4cFJRU1pBOW5hYnRxYTNWa0pxc25WZElhbUE0CmdXL3Ewd1E1TjBpSDIrSUM5RjVSNUJBK255VDBGSnJJZUcyRHpDbThlUTZUZXJMbGtmWWd1dHQxYXVZaE5DYnEKM0JkNk1ZQU1uYWRET3hDWDJIelhoTklmSXBMZDNCNHg5Z1RoNHdJREFRQUJBb0lCQVFDalUrK2M0LzdweWd1dgpLQnB6L1ZEZDBGWlNzZWNDem5QZGdlM1hvV2dHdTRFcnNRTDNaeTNaOU9kWnJLRWF3dlpOYzBOQkZDZS8wWUZLCnVkdFdrcDRLbHptdVY0ZnFCYUZ0UTd2RkZseHdRR015KzREVUp5UEg2b25iYmdnVDIvWWZPc2Z4cFV5QWtwVEwKbmphbFRrdndFckFjMjVYUkgxRGRmYnFRbVdRQTU5dlFxZ2JLRG1MaWtGZzhrQ3lvbnpDOG40Q3R6Z3lxeVFoOQpNaVE1bHRJdWY1Sk1uaTBGby9lWEVGT0VBcnZZMkdOQlViM2F3ckJXOWhSak03dGNSTU1rYis1TmRvdC8rajNMCmNoVk0rcmRrWlFoNlM5aC9JQ0R2RWx3Rm8xbDRSc0hya1AzdVI0RVN5QWhIZUxKQmk5YkxRZG5DWTlwRXFXdDgKc3BJcU05RUJBb0dCQVB6dVp4S2M4U2I0bW1TazVuSDNyN3FhOC9xNlR5cm4zaHNIVTlqNHpkZFpBdDhya0FUQgo1UlFiWjViaXAyeWc1bS93YTh3LzBoWFBXWmQ3YXNnY2o3RzFCRVhRRVpNenJ5TzhxcEk1NHVYT1JhQVJPVU5XCi9zdlhUZ0NyMmdhZnJ2aVZIcHczNC8zTERpZFErTThuZVJWaHdGVEdobzV3OXUzOFFwbnBaWkU1QW9HQkFQb2kKektOcDVTUHYxTlkvb3IxbW15Tm5sbVNqc251bFF3K1ozOWh1ek5ZSkRpeXIyajRodTUvbHpKRFZ1aUYzV3paVApuK0hyN3VnLzNwUDNaYWR4WlR3YW8vd0VSSURyWVFXTmR5aUppUHZQWWtrTDR0SHJNY2gvb0RYYlg5R001SW9ECm95ZjNmQjZHdStEYmtnWm81NmZHNFZ6OEtHZXgzdnhxZ2lOR1huZjdBb0dCQVBaZDBaQlR4cUhMTGJneTF6VFQKcWh2OXF3RGlVUkxkMzM0OFdQUFRCYzFwS2w3dk04MHVnRkJoa1RscmRPRmVxSmNJZkRmclFsdDBLVFJnUnRhOAoyMHFobzVQTTVCR2FHbEtaQnh4L3ZmOVNPSWQ5djJWVWE4TnA2TlRHa0F3N3BsY0VDVmpwSis2aHh4dU14NDRnClNOVUc3aXlsWTVPRGZVSzZvTFVDbnFnaEFvR0FWV016d0VVUjk2YVRYVi96eWZ3UTBaRTNBYnZ2M2MyWWl1YlkKUnlYcnZ0VHdoY2RVaFFrMjUycW0zbnBYUTcxZTRiakNSM2ttNFJtTWZhNWlnVHB3ZUlnUG1xUktUa2dMb3IyYwpBN2FQa0laRzR2Q3Z5VUVraVhFbjI3cTdodWsxeXZkYTV2WFE1UXJSYi8wRWFETy9nTUtmaEFLQU9JVzd2U2NPCnJjUUQwNmtDZ1lFQTBiQUZsc0QvNHp3M3R2VzRuUzlJMjhrb1pSa3RoNHhpVjE2SldzTk5lbVhsL3BGSk5XdDMKWEtIeHhEdEc2WkpYOVhxREJiMlpCZEJBRGNUb3k1RTlLZVlVcThQMHEwMkttS0E1RVlteDRhMEIrTjgwWlM1Swo1aFI0UVFkNk1sTTJmS0c3QWJvek44dTUvSkRiRU80QXc1OTZKdkI1ZEM0MCtjYWxwenYrV0E0PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

  Taiwan-LCG2_K8S_job.yaml: |+
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: grid-job
    spec:
      ttlSecondsAfterFinished: 172800
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: atlas-grid-centos7
              image: atlasadc/atlas-grid-centos7
              env:
                - name: computingSite
                  value: "$computingSite"
                - name: pandaQueueName
                  value: "$pandaQueueName"
                - name: proxySecretPath
                  value: "$proxySecretPath"
                - name: proxyContent
                  value: "$proxyContent"
                - name: workerID
                  value: "$workerID"
                - name: logs_frontend_w
                  value: "$logs_frontend_w"
                - name: logs_frontend_r
                  value: "$logs_frontend_r"
                - name: resourceType
                  value: "$resourceType"
                - name: HARVESTER_WORKER_ID
                  value: "$HARVESTER_WORKER_ID"
                - name: HARVESTER_ID
                  value: "$HARVESTER_ID"
                - name: PANDA_JSID
                  value: "$PANDA_JSID"
                - name: TMPDIR
                  value: "/root"
                - name: PILOT_NOKILL
                  value: "True"
              command: ["/usr/bin/bash"]
              args: ["-c", "cd; wget https://raw.githubusercontent.com/HSF/harvester/k8s_analysis/pandaharvester/harvestercloud/pilots_starter.py; chmod 755 pilots_starter.py; ./pilots_starter.py || true"]
              volumeMounts:
                - name: atlas
                  mountPath: /cvmfs/atlas.cern.ch
                  readOnly: true
                - name: atlas-condb
                  mountPath: /cvmfs/atlas-condb.cern.ch
                  readOnly: true
                - name: atlas-nightlies
                  mountPath: /cvmfs/atlas-nightlies.cern.ch
                  readOnly: true
                - name: sft
                  mountPath: /cvmfs/sft.cern.ch
                  readOnly: true
                - name: grid
                  mountPath: /cvmfs/grid.cern.ch
                  readOnly: true
                - name: proxy-secret
                  mountPath: /proxy
                  readOnly: true
          volumes:
            - name: atlas
              hostPath:
                path: /cvmfs/atlas.cern.ch
                type: Directory
            - name: atlas-condb
              hostPath:
                path: /cvmfs/atlas-condb.cern.ch
                type: Directory
            - name: atlas-nightlies
              hostPath:
                path: /cvmfs/atlas-nightlies.cern.ch
                type: Directory
            - name: sft
              hostPath:
                path: /cvmfs/sft.cern.ch
                type: Directory
            - name: grid
              hostPath:
                path: /cvmfs/grid.cern.ch
                type: Directory
            - name: proxy-secret
              secret:
                  secretName: proxy-secret

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: asgct1k8s
