apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-deployment
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
  labels:
    app: harvester
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: harvester
  template:
    metadata:
      name: harvester-pod
      labels:
        app: harvester
    spec:
      containers:
        - name: harvester-container
          image: pandawms/harvester:centos7
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            -  harvester_start.sh
          env:
          - name: RESTART_CYCLE
            value: '86400'
          volumeMounts:
          - name: panda-config
            mountPath: /usr/etc/panda
            readOnly: False
          - name: sysconfig-config
            mountPath: /usr/etc/sysconfig
            readOnly: True
      volumes:
        - name: panda-config
          projected:
            sources:
            - configMap:
                name: panda-common
            - configMap:
                name: panda-harvester
            - configMap:
                name: panda-queue
            - configMap:
                name: panda-uwsgi
            - configMap:
                name: panda-logroate
            - configMap:
                name: submitter-config
            - secret:
                name: proxy-file
        - name: sysconfig-config
          configMap:
            name: sysconfig-config
      restartPolicy: Always
      dnsConfig:
        nameservers:
          - {{ .Values.DNSserver }}
