apiVersion: v1
kind: Service
metadata:
  name: mariadb
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: {{ .Values.mariadb.clusterIP }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        imagePullPolicy: "Always"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mariadb.RootPassword }}
        - name: MYSQL_DATABASE
          value: HARVESTER
        - name: MYSQL_USER
          value: harvester
        - name: MYSQL_PASSWORD
          value: {{ .Values.mariadb.Password }}
        ports:
        - containerPort: 3306

